### ISSUE TITLE
建议添加一个可以运行的demo

### ISSUE THREAD

**Issue by jiyuren** [liuhuagui/smalldoc#8]
建议添加一个可以运行的springboot demo，目前集成路径访问不到，资源文件映射都不知道怎么写了

**Comment by liuhuagui** [comment]
多模块项目?

**Comment by jiyuren** [comment]
> 多模块项目?
是的，加上shiro需要手动添加资源映射，没有运行起来，不知道能不能把jar中的实体类的字段给解析出来

**Comment by liuhuagui** [comment]
```yml
smalldoc:
  source-paths: #额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
    - 'D:\Workspaces\myBeanProject\my-bean\src\main\java'
    - 'D:\Maven\Repositories\repository\com\aliyun\aliyun-java-sdk-core\3.5.0'
```
 尝试一下

**Comment by jiyuren** [comment]
> ```yaml
> smalldoc:
>   source-paths: #额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
>     - 'D:\Workspaces\myBeanProject\my-bean\src\main\java'
>     - 'D:\Maven\Repositories\repository\com\aliyun\aliyun-java-sdk-core\3.5.0'
> ```
> 
> 尝试一下

目前是项目运行我访问不到路径，新建一个普通的没有过多配置的项目，我也访问不到index.html啊

**Comment by liuhuagui** [comment]
报错没有？ 可以展示你的配置和访问路径吗

**Comment by jiyuren** [comment]
> 报错没有？ 可以展示你的配置和访问路径吗

`server:
  port: 8090

logging.level.org.springframework.boot.autoconfigure: ERROR

logging:
  config: classpath:log4j2-test.xml

smalldoc:
  source-paths: #额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
    - 'D:\workspace\jinmi\java\testjar\test-web\src\main\java\'
  packages:
    - qcom.jiyuren.web.controller
  project-name: 我的文档
  enabled: true #默认为true
  url-pattern: /smalldoc/* #默认为/smalldoc/*`
http://127.0.0.1:8090/smalldoc

**Comment by liuhuagui** [comment]
```
spring: 
  profiles:
    active: dev
```
接口文档默认是在dev环境中使用的

**Comment by jiyuren** [comment]
> ```
> spring: 
>   profiles:
>     active: dev
> ```
> 
> 接口文档默认是在dev环境中使用的

配置了一下，果然可以运行了，但是建议取消这个dev环境配置，因为多环境配置中加入有自定义的环境呢，这样就需要生成静态html直接预览了，但是实体类映射字段，都需要手动@{fn1,fn2,...}才能显示出请求参数

**Comment by liuhuagui** [comment]
```yml
spring: 
  profiles:
    active: dev,prod,test,custom #支持多配置，逗号隔开即可
```
`@{fn1,fn2,...}` 的使用是为了解决参数字段 **required** 问题 —— 尽管是同一个实体类，但是不同接口需要的字段参数不尽相同，不过放心，对于返回参数，所有字段都会显示出来。
